version: '3.8'

services:
  rasa: 
    image: rasa/rasa:3.6.2
    container_name: rasa
    ports:
      - "5005:5005"
    volumes:
     - ./domain.yml:/app/domain.yml
     - ./config.yml:/app/config.yml
     - ./endpoints.yml:/app/endpoints.yml
     - ./credentials.yml:/app/credentials.yml
     - ./data:/app/data
     - ./models:/app/models
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug
      - --model
      - /app/models
    depends_on:
      - action_server
  action_server:
    build:
        context: ./actions
    container_name: rasa_actions
    ports:
      - "5055:5055"
    volumes:
     - ./actions:/app/actions
    # command: ["start", "--actions", "actions"]