version: '3.0'
services:
  rasa:
    container_name: "api_rasa_server"
    image: rasa/rasa:3.2.4-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    entrypoint: ["/bin/sh","-c"]
    command: 
      - "rasa run --enable-api --credentials credentials.yml --cors '*'"
    networks:
      - network-api-v1

  # rasa-actions:
  #   container_name: "api_rasa_actions"
  #   # image: rasa/rasa-sdk
  #   build: 
  #     context: ./actions
  #     dockerfile: Dockerfile
  #   # ports: 
  #   #   - 5055:5055 
  #   # volumes:
  #   #   - ./actions:/app/actions
  #   # networks:
  #   #   - my-network

networks:
  network-api-v1:
    driver: bridge